"""Data model definitions"""
from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum


class TaskStatus(str, Enum):
    pending = "pending"
    in_progress = "in_progress"
    review = "review"
    completed = "completed"
    rejected = "rejected"


class AgentConfig(BaseModel):
    """Agent configuration"""
    id: str
    role: str
    system_prompt: str
    tools: list[str] = Field(default_factory=list)
    skills: list[str] = Field(default_factory=list)  # selected skill names
    plugins: list[str] = Field(default_factory=list)  # selected plugin names, e.g. ["playwright", "github"]
    provider: str = "claude"
    model: Optional[str] = None  # e.g. "claude-sonnet-4-6", "claude-opus-4-6"
    role_type: Optional[str] = None  # "planner" | "executor" | "reviewer" | custom


class TeamConfig(BaseModel):
    """Team configuration"""
    name: str
    agents: list[AgentConfig]
    max_retries: int = 3
    execution_mode: str = "sequential"  # "sequential" | "parallel"


class TaskItem(BaseModel):
    """Task item"""
    id: str
    description: str
    assignee: str
    depends_on: list[str] = Field(default_factory=list)
    output: Optional[str] = None
    status: TaskStatus = TaskStatus.pending


class SprintPlan(BaseModel):
    """Sprint plan generated by Manager"""
    goal: str
    tasks: list[TaskItem]
    constraints: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)


class RunStatus(BaseModel):
    """Run status"""
    id: str
    team_name: str
    status: str  # "idle" | "running" | "completed" | "failed"
    current_task: Optional[str] = None
    completed_tasks: list[str] = Field(default_factory=list)
    retry_count: int = 0


class FileChangeEvent(BaseModel):
    """File change event"""
    type: str = "file_change"
    change: str  # "created" | "modified" | "deleted"
    path: str


class AgentActivityEvent(BaseModel):
    """Agent activity event"""
    type: str = "agent_activity"
    agent_id: str
    action: str  # "thinking" | "completed"
    detail: str = ""


class WSMessage(BaseModel):
    """WebSocket message unified format"""
    type: str
    data: dict = Field(default_factory=dict)


class RunRecord(BaseModel):
    """Run history record"""
    id: str
    template_id: Optional[str] = None
    prompt: str
    goal: Optional[str] = None
    status: str = "running"  # "running" | "completed" | "failed"
    start_time: str = ""
    end_time: Optional[str] = None
    tasks_summary: list[dict] = Field(default_factory=list)
    detail: str = ""
    output_files: list[dict] = Field(default_factory=list)  # [{"path": ..., "size": ..., "action": "created"|"modified"}]
